ballerine-io/ballerine

README.md

Fixed a number of typos within ballerine/README.md

(docs): fixed README.md typos

---

README.md
sdks/web-sdk/README.md
sdks/web-sdk/examples/sdk/index.html
sdks/web-sdk/src/dev.ts
sdks/web-sdk/src/lib/atoms/Image/Image.svelte
sdks/web-sdk/src/lib/atoms/Overlay/Overlay.svelte
sdks/web-sdk/src/lib/atoms/VideoContainer/VideoContainer.svelte
sdks/web-sdk/src/lib/default-configuration/translation.json
sdks/web-sdk/src/lib/organisms/DocumentOptions/DocumentOptions.svelte
sdks/web-sdk/src/lib/pages/DocumentPhoto.svelte
sdks/web-sdk/src/lib/pages/DocumentPhotoBack.svelte
sdks/web-sdk/src/lib/pages/Selfie.svelte
sdks/web-sdk/src/main.ts
sdks/web-sdk/src/types/BallerineSDK.ts

fix(ui): overlay fix, kyb fixes

---

README.md

Added auto-updating badges to the top of the page.

Dynamic social badges using sheilds.io

---

README.md

Added URLs to all of the badges.

Fixed badges urls on README.md

---

sdks/web-sdk/src/lib/default-configuration/translation.json
sdks/web-sdk/src/lib/organisms/DocumentOptions/DocumentOptions.svelte
sdks/web-sdk/src/lib/pages/DocumentStart.svelte
sdks/web-sdk/src/lib/services/camera-manager/index.ts
sdks/web-sdk/src/lib/services/camera-manager/utils.ts

add no camera access toast message and not go to the error page
- [] …

fix: 🐛 add no camera access message

---

sdks/web-sdk/src/lib/services/camera-manager/utils.ts

fixes android white camera screen bug

fix(androidcam): close streams after asking for camera permessions

---

apps/backoffice/src/pages/users/components/SubjectList/SubjectList.tsx

Backoffice: Fix list item background

fix(bo users-list): fix list item bg

---

apps/backoffice/src/App.tsx
apps/backoffice/src/components/layout/header/index.tsx
apps/backoffice/src/pages/users/components/SubjectContent.tsx

Changes SubjectContent to scroll independently from the SubjectList.
* Local dev environment using Chrome
- [o] I have made corresponding changes to the documentation

SubjectContent content scroll

---

sdks/web-sdk/src/Routes.svelte

fix(svg): fix svg

---

apps/backoffice/README.md

Added link to main repo and minor fixes

---

.changeset/silly-numbers-confess.md

ci(npm): pr for releasing web-sdk v1.2.3

---

websites/docs/src/config.ts
websites/docs/src/pages/en/learn/case-management.md
websites/docs/src/pages/en/learn/sdk-backend-configuration.md
websites/docs/src/pages/en/learn/sdk-events.md
websites/docs/src/pages/en/learn/sdk-translations.md
websites/docs/src/pages/en/learn/sdk-ui-configuration.md
websites/docs/src/pages/en/learn/workflow-builder-and-rule-engine.md

Added markdown in websites/docs for backend config, flow events, and customizing the UI.
* Fedora desktop locally in Chrome

Document backend config, events, and UI

---

sdks/web-sdk/src/dev.ts
sdks/web-sdk/src/lib/contexts/navigation/hooks.ts
sdks/web-sdk/src/lib/molecules/NavigationButtons/NavigationButtons.svelte

Fix(navigation-hooks): fix passport step

---

sdks/web-sdk/src/App.svelte
sdks/web-sdk/src/dev.ts
sdks/web-sdk/src/lib/atoms/MetricsPixel/MetricsPixel.svelte
sdks/web-sdk/src/lib/configuration/configuration.ts
sdks/web-sdk/src/lib/contexts/configuration/types.ts
sdks/web-sdk/src/types/BallerineSDK.ts

Transparent pixel based analytics

feat(web-sdk): transparent pixel based analytics

---

sdks/web-sdk/examples/standalone-future/index.html

One of the tasks in enhancing the future KYC example is to change the font color of the paragraph to white.
* [Link to issue](https://github.com/ballerine-io/ballerine/issues/102).
* N/A.
* Ran the flow in my local environment.
* [Picture of welcome page](https://ibb.co/W2HG3y4).

feat(future_example): change paragraph text color for future example

---

README.md

docs(readme.md): fixed typos, capitalization and spacing consistency

---

websites/docs/src/pages/en/learn/kit.md

docs(kit.md): removed align center and fixed minor typos

---

README.md

Our new readme.md page, elaborating on the capabilities of Ballerine's open-source rules & workflow engine.

New Readme.md

---

websites/docs/src/pages/en/learn/kit.md

All page had center alignment.
Kept it only on the title.

kept center align only on title

---

packages/workflow-core/src/index.ts
packages/workflow-core/src/lib/index.ts
packages/workflow-core/src/lib/types.ts
packages/workflow-core/src/lib/workflow-runner.ts
pnpm-lock.yaml
sdks/workflow-browser-sdk/package.json
sdks/workflow-browser-sdk/src/index.ts
sdks/workflow-browser-sdk/src/lib/enums.ts
sdks/workflow-browser-sdk/src/lib/index.ts
sdks/workflow-browser-sdk/src/lib/types.ts
sdks/workflow-browser-sdk/src/lib/workflow-browser-sdk.ts

Readd error handling to workflow-browser-sdk

---

.changeset/lucky-eggs-rhyme.md
packages/rules-engine/package.json
packages/rules-engine/tsconfig.json
pnpm-lock.yaml
sdks/workflow-node-sdk/package.json
sdks/workflow-node-sdk/tsconfig.json

Fixed path to types from ./build/types to ./dist/types

---

README.md

Changed website link to direct to main website

---

.vscode/launch.json
pnpm-lock.yaml
services/workflows-service/package.json
services/workflows-service/src/main.ts
services/workflows-service/src/workflow/workflow.service.ts

fix(wf-service): intent

---

apps/backoffice-v2/src/api/workflows.ts
apps/backoffice-v2/src/components/organisms/Subject/Subject.Actions.tsx
apps/backoffice-v2/src/components/organisms/Subject/hooks/useActions/useActions.tsx
apps/backoffice-v2/src/lib/react-query/mutations/useRejectEndUserMutation/useRejectEndUserMutation.tsx
services/workflows-service/src/workflow/dtos/workflow-event-input.ts
services/workflows-service/src/workflow/workflow.service.ts

WIP - Reduce tech debt in the workflows service

---

.github/workflows/publish-images.yml
services/workflows-service/Dockerfile
services/workflows-service/src/main.ts

Publish workflows-service to container registry 

---

pnpm-lock.yaml
services/workflows-service/package.json
services/workflows-service/src/app.module.ts
services/workflows-service/src/main.ts

feat: integrated nestjs devtools to workflow-service

---

apps/backoffice-v2/.prettierrc.cjs
apps/backoffice-v2/package.json
apps/backoffice-v2/src/components/organisms/Header/Header.BottomActions.tsx
apps/backoffice-v2/src/components/organisms/Header/Header.Logo.tsx
apps/backoffice-v2/src/components/organisms/Header/Header.Navbar.tsx
apps/backoffice-v2/src/components/organisms/Subject/Subject.Actions.tsx
apps/backoffice-v2/src/components/organisms/Subject/Subject.Content.tsx
apps/backoffice-v2/src/components/organisms/SubjectsList/SubjectsList.Item.tsx
apps/backoffice-v2/src/components/organisms/SubjectsList/SubjectsList.tsx
apps/backoffice-v2/src/components/pages/Individual/Individual.page.tsx
apps/backoffice-v2/src/components/pages/Individual/hooks/useIndividual/useIndividual.tsx

This PR creates the base for the backoffice new skeleton UI and approve/reject per document.
* Each block renders the same information
* Locally in browser - tested in Chrome

Change individual view to render tasks as blocks

---

apps/backoffice-v2/src/components/organisms/Modal/Modal.tsx
apps/backoffice-v2/src/components/organisms/SubjectsList/SubjectsList.tsx
pnpm-lock.yaml
services/workflows-service/prisma/migrations/20230510140112_add_resolved_at_to_workflow_runtimes/migration.sql
services/workflows-service/prisma/schema.prisma
services/workflows-service/src/workflow/dtos/workflow-definition-update-input.ts
services/workflows-service/src/workflow/workflow.service.ts

Add`resolvedAt` to `WorkflowRuntimeData` model

---

services/workflows-service/prisma/migrations/20230511093245_change_status_to_be_enum_in_workflow_runtime_data/migration.sql
services/workflows-service/prisma/schema.prisma
services/workflows-service/src/workflow/dtos/workflow-definition-update-input.ts

Create enum `WorkflowRuntimeDataStatus`

---

apps/backoffice-v2/.env.example
services/workflows-service/src/app.module.ts
services/workflows-service/src/auth/session-auth.middleware.ts
services/workflows-service/src/main.ts

API versioning

---

services/workflows-service/prisma/schema.prisma
services/workflows-service/src/global.d.ts
services/workflows-service/src/schemas/documents/GH.ts
services/workflows-service/src/types.ts
services/workflows-service/src/workflow/enrich-workflow-runtime-data.ts
services/workflows-service/src/workflow/schemas/context.d.ts
services/workflows-service/src/workflow/schemas/default-context-schema.json
services/workflows-service/src/workflow/workflow.service.ts

feat(documents): add documents properties schema

---

apps/backoffice-v2/src/components/pages/Individual/hooks/useIndividual/useIndividual.tsx
services/workflows-service/src/main.ts

Revision state

---

apps/backoffice-v2/src/components/atoms/AssignButton/AssignButton.tsx
apps/backoffice-v2/src/components/atoms/Checkbox/Checkbox.Item.tsx
apps/backoffice-v2/src/components/organisms/SubjectsList/SubjectsList.tsx
apps/backoffice-v2/src/components/organisms/SubjectsList/hooks/useSubjectsList/useSubjectsList.tsx
apps/backoffice-v2/src/components/templates/AuthenticatedLayout/hooks/useAuthenticatedLayout/useAuthenticatedLayout.tsx
apps/backoffice-v2/src/hooks/useSelectEntityFilterOnMount/useSelectEntityFilterOnMount.tsx
apps/backoffice-v2/src/lib/react-query/queries/useEndUsersWithWorkflowsQuery/useEndUsersWithWorkflowsQuery.tsx

The filter was visible in the URL and the filter was applied but the correlating checkbox was not checked.
- [] New and …

Fix default filters not checked on mount

---

apps/backoffice-v2/src/components/organisms/SubjectsList/hooks/useSubjectsList/useSubjectsList.tsx
apps/backoffice-v2/src/components/pages/Individuals/Individuals.route.tsx
apps/backoffice-v2/src/components/pages/Individuals/pre-search-filters.ts
services/workflows-service/scripts/seed.ts

Remove entity type filter

---

apps/backoffice-v2/package.json
apps/backoffice-v2/src/components/atoms/Alert/Alert.Description.tsx
apps/backoffice-v2/src/components/atoms/Alert/Alert.Title.tsx
apps/backoffice-v2/src/components/atoms/Alert/Alert.tsx
apps/backoffice-v2/src/components/atoms/Input/Input.tsx
apps/backoffice-v2/src/components/atoms/Input/types.ts
apps/backoffice-v2/src/components/atoms/Label/Label.tsx
apps/backoffice-v2/src/components/organisms/_Form/_Form.tsx
apps/backoffice-v2/src/components/pages/SignIn/SignIn.page.tsx
apps/backoffice-v2/src/lib/utils.ts
pnpm-lock.yaml

New Sign In page / form design

---

apps/backoffice-v2/src/hooks/useSelectEndUserOnMount/useSelectEndUserOnMount.tsx
apps/backoffice-v2/src/hooks/useSort/sort.ts
apps/backoffice-v2/src/lib/react-query/queries/useFirstEndUserIdQuery/useFirstEndUserIdQuery.tsx

Improved behavior on selecting an initial entity, especially after sign in.
- [] My changes generate no new warnings and …

Select initial entity on mount / after sign in

---

apps/backoffice-v2/src/components/pages/Individual/hooks/useIndividual/useIndividual.tsx

Disable action buttons of documents with decision#386

---

apps/backoffice-v2/src/components/pages/Individual/hooks/useIndividual/useIndividual.tsx

duplicate images fix

---

apps/backoffice-v2/src/components/pages/Individual/hooks/useIndividual/useIndividual.tsx
pnpm-lock.yaml

update case state logic to include relevant information

Blokh/feat/show assign UI 

---

apps/backoffice-v2/src/components/organisms/Subject/Subject.Actions.tsx
apps/backoffice-v2/src/components/organisms/Subject/interfaces.ts
apps/backoffice-v2/src/components/pages/Individual/Individual.page.tsx
apps/backoffice-v2/src/components/pages/Individual/hooks/useIndividual/useIndividual.tsx
services/workflows-service/scripts/seed.ts

Hide case action buttons configuration

---

apps/backoffice-v2/src/components/pages/Individual/hooks/useIndividual/useIndividual.tsx
apps/backoffice-v2/src/lib/react-query/mutations/useUpdateWorkflowByIdMutation/useUpdateWorkflowByIdMutation.tsx

Workflow context optimistic updates

---

.github/workflows/publish-images-dev.yml
.github/workflows/publish-images.yml

Fix Sentry source maps upload

---

apps/backoffice-v2/src/components/organisms/Header/Header.BottomActions.tsx

Changed agent email in the bottom left from user email to first name + last name
#409 
pnpm dev
https://user-images.githubusercontent.com/55488549/240649294-3ebb02c5-5af2-4fee-aeea-6c5f2df466c2.png

refactor(backoffice-v2): change agent email in the bottom left to first name + last name

---

apps/backoffice-v2/src/components/pages/Root/Root.error.tsx
apps/backoffice-v2/src/components/pages/Root/Root.route.tsx
apps/backoffice-v2/src/components/pages/SignIn/SignIn.page.tsx

Added an error component with a link back to the home page.
Navigation button works as a recovery from the error.
* ![image](https://github.com/ballerine-io/ballerine/assets/61207713/b75abae5-aaf0-4193-8387-a59040b555d2)

Root error component

---

apps/backoffice-v2/src/components/pages/Individual/Individual.page.tsx
services/workflows-service/scripts/seed.ts

Did not previously display any content in the individual view prior to this change. Now there's also a UI indicator in case no tasks were built from the context

Populate individuals context and context documents in seed

---

services/workflows-service/src/events/document-changed-webhook-caller.ts
services/workflows-service/src/global.d.ts
services/workflows-service/src/workflow/workflow-event-emitter.service.ts

Alert on webhook failure

---

apps/backoffice-v2/src/components/organisms/SubjectsList/SubjectsList.tsx
services/workflows-service/src/workflow/workflow-runtime-data.repository.ts
services/workflows-service/src/workflow/workflow.controller.external.ts
services/workflows-service/src/workflow/workflow.service.ts

The workflows controller now has an endpoint which can be used to get a workflow's status by sending its context object. …

Add an endpoint to receive a workflow's context

---

apps/backoffice-v2/package.json
packages/common/package.json
packages/config/eslintrc.base.cjs
packages/rules-engine/package.json
packages/workflow-core/package.json
sdks/web-ui-sdk/package.json
sdks/workflow-browser-sdk/package.json
sdks/workflow-node-sdk/package.json
services/workflows-service/package.json
websites/docs/package.json

This PR adds & configure ESLint unused import plugin to [ballerine](https://github.com/ballerine-io/ballerine) project
[https://github.com/ballerine-io/ballerine/issues/311](https://github.com/ballerine-io/ballerine/issues/311)
N/A
* https://www.npmjs.com/package/eslint-plugin-unused-imports

chore: add ESLint unused import plugin

---

.github/actions/build-action/action.yml
.github/actions/format-action/action.yml
.github/actions/lint-action/action.yml
.github/actions/test-action/action.yml
.github/workflows/release.yml

Upgrade node version from 16 to 18.12.1 in CI
Closes: #470 
Upgrade node version from 16 to 18.12.1 in CI

Upgrade node version from 16 to 18.12.1 in CI

---

apps/backoffice-v2/src/routes/Entity/components/Case/Case.Actions.tsx

Removes the animation on the entity's name in the actions component

Remove name animation

---

apps/backoffice-v2/src/pages/Entities/components/Cases/Cases.tsx
apps/backoffice-v2/src/pages/Entity/hooks/useEntity/utils.ts
services/workflows-service/scripts/workflows/index.ts
services/workflows-service/src/common/filters/prisma-client-validation-filter/utils/PrismaValidationExceptionParser.ts

add kyb w/ external request

---

README.md

Update README.md mistakes

---

apps/backoffice-v2/package.json
apps/backoffice-v2/src/common/components/atoms/AssignButton/AssignButton.tsx
apps/backoffice-v2/src/common/components/molecules/DetailsGrid/DetailsGrid.tsx
apps/backoffice-v2/src/common/components/organisms/ImageViewer/ImageViewer.Item.tsx
apps/backoffice-v2/src/pages/Entities/components/Cases/Cases.tsx
apps/backoffice-v2/src/pages/Entity/components/Case/Case.Actions.tsx
services/workflows-service/src/events/document-changed-webhook-caller.ts
services/workflows-service/src/workflow/workflow.service.ts

- feat(wrofkflow webhooks): add timestamps to wrokflow webhooks
- feat(wh): add timestamps to workflows webhooks
- fixed tests
- fixed tests
- [] I have made corresponding changes …

add timestamps to workflow webhooks

---

pnpm-lock.yaml
websites/docs/astro.config.mjs
websites/docs/package.json
websites/docs/src/components/LeftSidebar/LeftSidebar.astro

fix(docs): update astro

---

apps/backoffice-v2/src/pages/Entity/components/CallToAction/CallToAction.tsx
apps/backoffice-v2/src/pages/Entity/components/CallToAction/hooks/useCallToActionLogic/useCallToActionLogic.tsx

Backoffice - Merge reject and revision into a single dialog

---

apps/backoffice-v2/src/pages/Entity/components/Case/Case.Documents.tsx
apps/backoffice-v2/src/pages/Entity/components/Case/hooks/useDocuments/useDocuments.tsx

Backoffice - added rotate button to selected image

---

apps/backoffice-v2/src/domains/workflows/fetchers.ts
apps/backoffice-v2/src/pages/Entity/components/EditableDetails/EditableDetails.tsx
apps/backoffice-v2/src/pages/Entity/components/Heading/Heading.tsx
apps/backoffice-v2/src/pages/Entity/components/Heading/interfaces.ts
apps/backoffice-v2/src/pages/Entity/components/NestedComponent/NestedComponent.tsx
apps/backoffice-v2/src/pages/Entity/components/NestedComponent/interfaces.ts
apps/backoffice-v2/src/pages/Entity/components/NestedDetails/NestedDetails.tsx
apps/backoffice-v2/src/pages/Entity/components/NestedDetails/interfaces.ts
apps/backoffice-v2/src/pages/Entity/hooks/useEntity/components.tsx
apps/backoffice-v2/src/pages/Entity/hooks/useEntity/useEntity.tsx

feat(backoffice-v2): added a content block to display plugin output

---

apps/backoffice-v2/src/pages/Entity/components/CallToAction/hooks/useCallToActionLogic/useCallToActionLogic.tsx
apps/backoffice-v2/src/pages/Entity/hooks/useEntity/useEntity.tsx

- Disable field editing on tasks with a decision
- Renamed reject dialog to ask to resubmit and block actions
- [] New …

Backoffice - feedback updates

---

examples/headless-example/.gitignore
examples/headless-example/e2e/smoke.spec.ts
examples/headless-example/package.json
examples/headless-example/playwright.config.ts
examples/headless-example/src/components/SignUp.svelte
examples/headless-example/tsconfig.json
pnpm-lock.yaml

Catches instances of blank white page - in response to cases where there are logs in devtools and the app still runs.

Headless example - E2E smoke test 

---

apps/backoffice-v2/src/common/components/atoms/AssignButton/AssignButton.tsx
apps/backoffice-v2/src/pages/Entity/components/Case/Case.Actions.tsx
apps/backoffice-v2/src/pages/Entity/components/Case/hooks/useActions/useActions.tsx
services/workflows-service/src/workflow/workflow.controller.internal.ts
services/workflows-service/src/workflow/workflow.service.ts

* https://github.com/ballerine-io/ballerine/issues/598
- [] New and existing tests pass locally with my …

Disable ability to change assignment on a case with a decision

---

apps/workflows-dashboard/package.json
apps/workflows-dashboard/src/components/molecules/WorkflowsTable/WorkflowsTable.tsx
apps/workflows-dashboard/src/components/molecules/WorkflowsTable/columns.tsx
apps/workflows-dashboard/src/components/molecules/WorkflowsTable/components/ContextViewColumn/ContextViewColumn.tsx
apps/workflows-dashboard/src/components/molecules/WorkflowsTable/types.ts
apps/workflows-dashboard/src/components/molecules/WorkflowsTable/utils/merge-columns.ts
apps/workflows-dashboard/src/components/organisms/XstateVisualizer/XstateVisualizer.tsx
apps/workflows-dashboard/src/components/organisms/XstateVisualizer/index.ts
apps/workflows-dashboard/src/components/organisms/XstateVisualizer/utils/deserialize-state-definition.ts
apps/workflows-dashboard/src/domains/workflows/api/workflow/query-keys.ts
apps/workflows-dashboard/src/domains/workflows/api/workflow/workflow.api.ts
apps/workflows-dashboard/src/domains/workflows/api/workflow/workflow.types.ts
apps/workflows-dashboard/src/pages/Workflows/components/organisms/WorkflowsList/WorkflowsList.tsx
apps/workflows-dashboard/src/pages/Workflows/components/organisms/WorkflowsList/components/ViewWorkflow/ViewWorkflow.tsx
apps/workflows-dashboard/src/pages/Workflows/components/organisms/WorkflowsList/components/ViewWorkflow/index.ts
apps/workflows-dashboard/src/pages/Workflows/hooks/useWorkflowDefinitionQuery/index.ts
apps/workflows-dashboard/src/pages/Workflows/hooks/useWorkflowDefinitionQuery/useWorkflowDefinitionQuery.ts
pnpm-lock.yaml
services/workflows-service/src/workflow/workflow-runtime-list-item.model.ts
services/workflows-service/src/workflow/workflow.controller.external.ts

- Added `XstateVisualizer` component
- added workflow state colum to workflows table
- extended WorkflowTable api so columns could be modified from outer context
- added endpoint to fetch workflow definition
- [] I have made …

feat: added x-state visualizer to wf table & added wf definition endpoint

---

apps/backoffice-v2/src/domains/workflows/mock-service-worker/workflows/workflows.controller.ts
packages/workflow-core/src/lib/types.ts
packages/workflow-core/src/lib/workflow-runner.ts
pnpm-lock.yaml
sdks/workflow-node-sdk/src/lib/types.ts
sdks/workflow-node-sdk/src/lib/workflow-node-sdk.test.ts
services/workflows-service/package.json
services/workflows-service/prisma/migrations/20230704114338_check_policy/migration.sql
services/workflows-service/scripts/seed.ts
services/workflows-service/src/workflow/workflow.controller.internal.ts
services/workflows-service/src/workflow/workflow.service.ts

Child workflows API updates

---

apps/backoffice-v2/src/domains/workflows/mock-service-worker/workflows/workflows.controller.ts
packages/common/src/validations/workflow-validators/api-plugin.validator.test.ts
packages/common/src/validations/workflow-validators/webhook-plugin.validator.test.ts
packages/common/src/validations/workflow-validators/workflow-definition-validator.test.ts
packages/workflow-core/src/lib/plugins/external-plugin/types.ts
packages/workflow-core/src/lib/types.ts
packages/workflow-core/src/lib/workflow-runner.ts
pnpm-lock.yaml
sdks/workflow-node-sdk/src/lib/types.ts
sdks/workflow-node-sdk/src/lib/workflow-node-sdk.test.ts
services/workflows-service/.env.example
services/workflows-service/package.json
services/workflows-service/prisma/migrations/20230704114338_check_policy/migration.sql
services/workflows-service/scripts/seed.ts
services/workflows-service/scripts/workflows/e2e-dynamic-url-example.ts
services/workflows-service/scripts/workflows/kyc-dynamic-process-example.ts
services/workflows-service/src/workflow/workflow.controller.internal.ts
services/workflows-service/src/workflow/workflow.service.ts

childContextToCopy and parentContextToCopy

---

apps/workflows-dashboard/src/common/hooks/useSession/useSession.ts
apps/workflows-dashboard/src/components/atoms/HealthIndicator/HealthIndicator.tsx
apps/workflows-dashboard/src/components/molecules/MetricCard/MetricCard.tsx
apps/workflows-dashboard/src/components/molecules/WorkflowsTable/WorkflowsTable.tsx
apps/workflows-dashboard/src/pages/Overview/hooks/useCaseResolvingStatsQuery/useCaseResolvingStatsQuery.ts
apps/workflows-dashboard/src/pages/Overview/hooks/useUserStatsQuery/useUserStatsQuery.ts
apps/workflows-dashboard/src/pages/Overview/hooks/useUsersCaseResolvingStatsQuery/useUsersCaseResolvingStatsQuery.ts
apps/workflows-dashboard/src/pages/SignIn/components/SignInForm/SignInForm.tsx
apps/workflows-dashboard/src/pages/Workflows/components/molecules/AgentsActivityChart/AgentsActivityChart.tsx
apps/workflows-dashboard/src/pages/Workflows/components/providers/WorkflowsFiltersProvider/hooks/useWorkflowsQueryParams/useWorkflowsQueryParams.ts
apps/workflows-dashboard/vite.config.ts

- replaced imports with `*` notation to default imports to fix module resolution in prod build
- added preview port to vite config
- [] My changes generate no new warnings …

fix: fixed imports & added preview port to vite config

---

services/workflows-service/src/events/document-changed-webhook-caller.ts

fix(webhook-handler): null check on document changed

---

.changeset/config.json
.github/workflows/release.yml
apps/backoffice-v2/package.json
examples/headless-example/CHANGELOG.md
examples/headless-example/package.json
packages/common/CHANGELOG.md
packages/common/package.json
packages/common/src/schemas/documents/workflow/documents/schemas/GH.ts
packages/workflow-core/CHANGELOG.md
packages/workflow-core/package.json
pnpm-lock.yaml
sdks/web-ui-sdk/CHANGELOG.md
sdks/web-ui-sdk/package.json
sdks/workflow-browser-sdk/CHANGELOG.md
sdks/workflow-browser-sdk/package.json
services/workflows-service/CHANGELOG.md
services/workflows-service/package.json
services/workflows-service/prisma/migrations/20230711224250_add_enduser_type_change_business_address/migration.sql
services/workflows-service/scripts/seed.ts
websites/docs/package.json

feat(doc-schemas): add mtn statement

---

apps/workflows-dashboard/src/domains/user/api/user-stats/user-stats.api.ts
apps/workflows-dashboard/src/domains/user/api/user-stats/user-stats.types.ts
apps/workflows-dashboard/src/domains/user/api/users-stats/users-stats.types.ts
apps/workflows-dashboard/src/domains/workflows/api/workflow-metrics/workflow-metrics.types.ts
apps/workflows-dashboard/src/pages/Overview/components/molecules/UserStats/UserStats.tsx
apps/workflows-dashboard/src/pages/Overview/hooks/useUserStatsQuery/useUserStatsQuery.ts
apps/workflows-dashboard/src/pages/Workflows/components/molecules/AgentCasesChart/AgentCasesChart.tsx
apps/workflows-dashboard/src/pages/Workflows/components/molecules/CasesPerStatusChart/CasesPerStatusChart.tsx
apps/workflows-dashboard/src/pages/Workflows/components/organisms/metrics/AgentCasesStats/hooks/useUsersAssignedCasesStatsQuery/useUsersAssignedCasesStatsQuery.ts
apps/workflows-dashboard/src/pages/Workflows/components/organisms/metrics/CasesPerStatusStats/hooks/useCasesPerStatusQuery/useCasesPerStatusQuery.ts
services/workflows-service/src/metrics/common/types/base-query.params.ts
services/workflows-service/src/metrics/dto/get-users-assigned-cases-statistic.dto.ts
services/workflows-service/src/metrics/dto/get-workflow-runtimes-status-count.dto.ts
services/workflows-service/src/metrics/repository/metrics.repository.ts
services/workflows-service/src/metrics/repository/models/average-assignment-time.model.ts
services/workflows-service/src/metrics/repository/models/average-resolution-time.model.ts
services/workflows-service/src/metrics/repository/models/average-review-time.model.ts
services/workflows-service/src/metrics/repository/sql/aggregate-average-assignment-time.sql.ts
services/workflows-service/src/metrics/repository/sql/aggregate-average-resolution-time.sql.ts
services/workflows-service/src/metrics/repository/sql/aggregate-average-review-time.sql.ts
services/workflows-service/src/metrics/repository/sql/aggregate-users-assigned-cases-statistic.sql.ts
services/workflows-service/src/metrics/repository/sql/aggregate-workflow-runtime-status-case-count.sql.ts
services/workflows-service/src/metrics/repository/types/aggregate-average-assignment-time.ts
services/workflows-service/src/metrics/repository/types/aggregate-average-resolution-time.ts
services/workflows-service/src/metrics/repository/types/aggregate-average-review-time.ts
services/workflows-service/src/metrics/service/metrics.service.ts
services/workflows-service/src/metrics/service/models/user-workflow-processing-statistic.model.ts

- Updated SQL queries to handle BigInt
- updated models
- added `time` serialization in models
- updated Cases per status & Cases per agent so now they fetched for all time instead of 1 hour period
- updated related ednpoints & sql queries
- [] I have commented my code, particularly in …

fix: added biging serialization & updated models & FE types

---

apps/backoffice-v2/package.json
apps/backoffice-v2/src/pages/Entity/hooks/useEntity/utils.ts
examples/headless-example/CHANGELOG.md
examples/headless-example/package.json
packages/common/CHANGELOG.md
packages/common/package.json
packages/common/src/schemas/documents/workflow/documents/schemas/GH.ts
packages/workflow-core/CHANGELOG.md
packages/workflow-core/package.json
pnpm-lock.yaml
sdks/web-ui-sdk/CHANGELOG.md
sdks/web-ui-sdk/package.json
sdks/workflow-browser-sdk/CHANGELOG.md
sdks/workflow-browser-sdk/package.json
services/workflows-service/CHANGELOG.md
services/workflows-service/package.json
websites/docs/package.json

feat(docs): add docs schema type

---

apps/workflows-dashboard/src/pages/Overview/components/molecules/UsersResolvingStatsList/UsersResolvingStatsList.tsx
services/workflows-service/src/metrics/dto/get-user-workflow-processing-statistic.dto.ts
services/workflows-service/src/metrics/metrics.controller.ts
services/workflows-service/src/metrics/repository/metrics.repository.ts
services/workflows-service/src/metrics/repository/sql/aggregate-approval-rate.sql.ts
services/workflows-service/src/metrics/repository/sql/aggregate-average-assignment-time.sql.ts
services/workflows-service/src/metrics/repository/sql/aggregate-average-resolution-time.sql.ts
services/workflows-service/src/metrics/repository/sql/aggregate-average-review-time.sql.ts
services/workflows-service/src/metrics/repository/types/aggregate-average-assignment-time.ts
services/workflows-service/src/metrics/repository/types/aggregate-average-resolution-time.ts
services/workflows-service/src/metrics/repository/types/aggregate-average-review-time.ts
services/workflows-service/src/metrics/repository/types/get-user-approval-rate.params.ts
services/workflows-service/src/metrics/repository/types/get-user-average-assignment-time.params.ts
services/workflows-service/src/metrics/repository/types/get-user-average-resolution-time.params.ts
services/workflows-service/src/metrics/repository/types/get-user-average-review-time.params.ts
services/workflows-service/src/metrics/service/metrics.service.ts

Fixed queries:
- avg assignment time
- avg resolution time
- avg review time
- updated types & models
- fixed missing react key in wf dashboard
- [] My changes generate no …

fix: fixed wf processing stats queries, added missing key to user resolved cases list

---

packages/rules-engine/package.json
packages/rules-engine/src/index.ts
packages/rules-engine/src/lib/rule-engine.spec.ts
packages/rules-engine/src/lib/rule-engine.ts
packages/workflow-core/src/index.ts
packages/workflow-core/src/lib/plugins/common-plugin/child-workflow-plugin.ts
packages/workflow-core/src/lib/types.ts
packages/workflow-core/src/lib/workflow-runner.ts
pnpm-lock.yaml
services/workflows-service/package.json
services/workflows-service/scripts/seed.ts
services/workflows-service/scripts/workflows/index.ts
services/workflows-service/scripts/workflows/parent-kyb-workflow.ts
services/workflows-service/src/workflow/schemas/zod-schemas.ts
services/workflows-service/src/workflow/workflow.service.ts

generated jmespath rule engine + race condition fixing

---

packages/rules-engine/src/index.ts
packages/workflow-core/package.json
packages/workflow-core/src/lib/plugins/external-plugin/api-plugin.ts
packages/workflow-core/src/lib/plugins/external-plugin/kyb-plugin.ts
packages/workflow-core/src/lib/plugins/external-plugin/kyc-plugin.ts
packages/workflow-core/src/lib/types.ts
packages/workflow-core/src/lib/utils/context-validator/json-schema-validator.ts
packages/workflow-core/src/lib/workflow-runner.ts
pnpm-lock.yaml
services/workflows-service/scripts/workflows/e2e-dynamic-url-example.ts
services/workflows-service/scripts/workflows/kyc-dynamic-process-example.ts
services/workflows-service/scripts/workflows/parent-kyb-workflow.ts
services/workflows-service/src/workflow/types/index.ts
services/workflows-service/src/workflow/workflow.service.ts

feat: added kyb plugin

---

packages/ui/.gitignore
packages/ui/package.json
packages/ui/vite.config.ts
pnpm-lock.yaml

fix(packages/ui): renamed lib to dist

---

services/workflows-service/src/workflow/workflow.service.ts

Now covering the case where there's no select or include.
- [] New …

fix(workflows-service): added a default case for safeArgs (select include error)

---

apps/backoffice-v2/package.json
apps/backoffice-v2/src/pages/Entity/components/EditableDetails/EditableDetails.tsx

Testing demo deployment

---

websites/docs/src/pages/en/learn/back-office.md

chore: fix example
